#!/bin/bash

ORIGIN_URL=`git config --get remote.origin.url`
ORIGIN_CREDENTIALS=${ORIGIN_URL/\/\/github.com/\/\/$GITHUB_TOKEN@github.com}
COMMIT_MESSAGE=$(git log -1 --pretty=%B)

echo "Started deploying to the gh-pages branch."

echo "Creating clean gh-pages branch."
if [ `git branch | grep gh-pages` ]
then
  git branch -D gh-pages
fi
git checkout -b gh-pages

echo "Building site."
bower install
bundle exec jekyll build --destination temp || exit 1

echo "Removing old files"
find . -maxdepth 1 ! -name 'temp' ! -name '.git' ! -name '.gitignore' -exec rm -rf {} \;

mv temp/* . || exit 1
rm -R temp/ || exit 1

echo "Pushing content"
git config user.name "$USERNAME"
git config user.email "$EMAIL"

git add -fA || exit 1
git commit --allow-empty -m "$COMMIT_MESSAGE" || exit 1

git push -f -q "$ORIGIN_CREDENTIALS" gh-pages > /dev/null 2>&1

echo "Deployed Successfully"

echo "Checking out previous branch"
git checkout -
bower install

exit 0
