source "https://rubygems.org"

gem "autoprefixer-rails", "~> 6.1", ">= 6.1.0.1"
gem "jekyll", "~> 3.0", ">= 3.0.1"
gem "jekyll-assets", "~> 2.0"
gem "jekyll-sitemap", "~> 0.9.0"
gem "sass", "~> 3.4", ">= 3.4.19"
gem "uglifier", "~> 2.7", ">= 2.7.2"
